version: 0.2
env:
  shell: bash
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - apt-get update -y
      - apt-get install -y maven  
  # pre_build:
  #   commands:
  #     - echo "command"
  build:
    commands:
      - mvn clean install
  # post_build:
  #   commands:
  #     - echo "post build"
artifacts:
  base-directory: target
  files:
    - "**/*"